#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavisUberCarOrderHandler
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NavisUberPMCuong")]
	public partial class DataClasses2DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLst_LoaiXe(Lst_LoaiXe instance);
    partial void UpdateLst_LoaiXe(Lst_LoaiXe instance);
    partial void DeleteLst_LoaiXe(Lst_LoaiXe instance);
    partial void InsertLst_DatXe(Lst_DatXe instance);
    partial void UpdateLst_DatXe(Lst_DatXe instance);
    partial void DeleteLst_DatXe(Lst_DatXe instance);
    #endregion
		
		public DataClasses2DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["NavisUberPMCuong"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Lst_LoaiXe> Lst_LoaiXes
		{
			get
			{
				return this.GetTable<Lst_LoaiXe>();
			}
		}
		
		public System.Data.Linq.Table<Lst_DatXe> Lst_DatXes
		{
			get
			{
				return this.GetTable<Lst_DatXe>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lst_LoaiXe")]
	public partial class Lst_LoaiXe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_loai_xe;
		
		private string _ten_loai_xe;
		
		private string _so_ghe;
		
		private System.Nullable<int> _code;
		
		private string _mo_ta;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_loai_xeChanging(int value);
    partial void Onid_loai_xeChanged();
    partial void Onten_loai_xeChanging(string value);
    partial void Onten_loai_xeChanged();
    partial void Onso_gheChanging(string value);
    partial void Onso_gheChanged();
    partial void OncodeChanging(System.Nullable<int> value);
    partial void OncodeChanged();
    partial void Onmo_taChanging(string value);
    partial void Onmo_taChanged();
    #endregion
		
		public Lst_LoaiXe()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_loai_xe", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_loai_xe
		{
			get
			{
				return this._id_loai_xe;
			}
			set
			{
				if ((this._id_loai_xe != value))
				{
					this.Onid_loai_xeChanging(value);
					this.SendPropertyChanging();
					this._id_loai_xe = value;
					this.SendPropertyChanged("id_loai_xe");
					this.Onid_loai_xeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_loai_xe", DbType="NVarChar(100)")]
		public string ten_loai_xe
		{
			get
			{
				return this._ten_loai_xe;
			}
			set
			{
				if ((this._ten_loai_xe != value))
				{
					this.Onten_loai_xeChanging(value);
					this.SendPropertyChanging();
					this._ten_loai_xe = value;
					this.SendPropertyChanged("ten_loai_xe");
					this.Onten_loai_xeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_ghe", DbType="NVarChar(3)")]
		public string so_ghe
		{
			get
			{
				return this._so_ghe;
			}
			set
			{
				if ((this._so_ghe != value))
				{
					this.Onso_gheChanging(value);
					this.SendPropertyChanging();
					this._so_ghe = value;
					this.SendPropertyChanged("so_ghe");
					this.Onso_gheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="Int")]
		public System.Nullable<int> code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo_ta", DbType="NVarChar(200)")]
		public string mo_ta
		{
			get
			{
				return this._mo_ta;
			}
			set
			{
				if ((this._mo_ta != value))
				{
					this.Onmo_taChanging(value);
					this.SendPropertyChanging();
					this._mo_ta = value;
					this.SendPropertyChanged("mo_ta");
					this.Onmo_taChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lst_DatXe")]
	public partial class Lst_DatXe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _id_loai_xe;
		
		private string _sdt_nguoi_dat;
		
		private string _diem_bat_dau;
		
		private string _diem_ket_thuc;
		
		private double _lat_bat_dau;
		
		private double _long_bat_dau;
		
		private double _lat_ket_thuc;
		
		private double _long_ket_thuc;
		
		private System.DateTime _thoi_diem_dat_xe;
		
		private System.Nullable<System.DateTime> _thoi_diem_khoi_hanh;
		
		private System.Nullable<int> _id_xe;
		
		private System.Nullable<System.DateTime> _thoi_diem_ket_thuc;
		
		private System.Nullable<int> _status;
		
		private System.Nullable<int> _so_ghe;
		
		private int _id_dat_xe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_loai_xeChanging(System.Nullable<int> value);
    partial void Onid_loai_xeChanged();
    partial void Onsdt_nguoi_datChanging(string value);
    partial void Onsdt_nguoi_datChanged();
    partial void Ondiem_bat_dauChanging(string value);
    partial void Ondiem_bat_dauChanged();
    partial void Ondiem_ket_thucChanging(string value);
    partial void Ondiem_ket_thucChanged();
    partial void Onlat_bat_dauChanging(double value);
    partial void Onlat_bat_dauChanged();
    partial void Onlong_bat_dauChanging(double value);
    partial void Onlong_bat_dauChanged();
    partial void Onlat_ket_thucChanging(double value);
    partial void Onlat_ket_thucChanged();
    partial void Onlong_ket_thucChanging(double value);
    partial void Onlong_ket_thucChanged();
    partial void Onthoi_diem_dat_xeChanging(System.DateTime value);
    partial void Onthoi_diem_dat_xeChanged();
    partial void Onthoi_diem_khoi_hanhChanging(System.Nullable<System.DateTime> value);
    partial void Onthoi_diem_khoi_hanhChanged();
    partial void Onid_xeChanging(System.Nullable<int> value);
    partial void Onid_xeChanged();
    partial void Onthoi_diem_ket_thucChanging(System.Nullable<System.DateTime> value);
    partial void Onthoi_diem_ket_thucChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    partial void Onso_gheChanging(System.Nullable<int> value);
    partial void Onso_gheChanged();
    partial void Onid_dat_xeChanging(int value);
    partial void Onid_dat_xeChanged();
    #endregion
		
		public Lst_DatXe()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_loai_xe", DbType="Int")]
		public System.Nullable<int> id_loai_xe
		{
			get
			{
				return this._id_loai_xe;
			}
			set
			{
				if ((this._id_loai_xe != value))
				{
					this.Onid_loai_xeChanging(value);
					this.SendPropertyChanging();
					this._id_loai_xe = value;
					this.SendPropertyChanged("id_loai_xe");
					this.Onid_loai_xeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt_nguoi_dat", DbType="NChar(20)")]
		public string sdt_nguoi_dat
		{
			get
			{
				return this._sdt_nguoi_dat;
			}
			set
			{
				if ((this._sdt_nguoi_dat != value))
				{
					this.Onsdt_nguoi_datChanging(value);
					this.SendPropertyChanging();
					this._sdt_nguoi_dat = value;
					this.SendPropertyChanged("sdt_nguoi_dat");
					this.Onsdt_nguoi_datChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diem_bat_dau", DbType="NChar(255)")]
		public string diem_bat_dau
		{
			get
			{
				return this._diem_bat_dau;
			}
			set
			{
				if ((this._diem_bat_dau != value))
				{
					this.Ondiem_bat_dauChanging(value);
					this.SendPropertyChanging();
					this._diem_bat_dau = value;
					this.SendPropertyChanged("diem_bat_dau");
					this.Ondiem_bat_dauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diem_ket_thuc", DbType="NChar(255)")]
		public string diem_ket_thuc
		{
			get
			{
				return this._diem_ket_thuc;
			}
			set
			{
				if ((this._diem_ket_thuc != value))
				{
					this.Ondiem_ket_thucChanging(value);
					this.SendPropertyChanging();
					this._diem_ket_thuc = value;
					this.SendPropertyChanged("diem_ket_thuc");
					this.Ondiem_ket_thucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lat_bat_dau", DbType="Float NOT NULL")]
		public double lat_bat_dau
		{
			get
			{
				return this._lat_bat_dau;
			}
			set
			{
				if ((this._lat_bat_dau != value))
				{
					this.Onlat_bat_dauChanging(value);
					this.SendPropertyChanging();
					this._lat_bat_dau = value;
					this.SendPropertyChanged("lat_bat_dau");
					this.Onlat_bat_dauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_long_bat_dau", DbType="Float NOT NULL")]
		public double long_bat_dau
		{
			get
			{
				return this._long_bat_dau;
			}
			set
			{
				if ((this._long_bat_dau != value))
				{
					this.Onlong_bat_dauChanging(value);
					this.SendPropertyChanging();
					this._long_bat_dau = value;
					this.SendPropertyChanged("long_bat_dau");
					this.Onlong_bat_dauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lat_ket_thuc", DbType="Float NOT NULL")]
		public double lat_ket_thuc
		{
			get
			{
				return this._lat_ket_thuc;
			}
			set
			{
				if ((this._lat_ket_thuc != value))
				{
					this.Onlat_ket_thucChanging(value);
					this.SendPropertyChanging();
					this._lat_ket_thuc = value;
					this.SendPropertyChanged("lat_ket_thuc");
					this.Onlat_ket_thucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_long_ket_thuc", DbType="Float NOT NULL")]
		public double long_ket_thuc
		{
			get
			{
				return this._long_ket_thuc;
			}
			set
			{
				if ((this._long_ket_thuc != value))
				{
					this.Onlong_ket_thucChanging(value);
					this.SendPropertyChanging();
					this._long_ket_thuc = value;
					this.SendPropertyChanged("long_ket_thuc");
					this.Onlong_ket_thucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoi_diem_dat_xe", DbType="DateTime NOT NULL")]
		public System.DateTime thoi_diem_dat_xe
		{
			get
			{
				return this._thoi_diem_dat_xe;
			}
			set
			{
				if ((this._thoi_diem_dat_xe != value))
				{
					this.Onthoi_diem_dat_xeChanging(value);
					this.SendPropertyChanging();
					this._thoi_diem_dat_xe = value;
					this.SendPropertyChanged("thoi_diem_dat_xe");
					this.Onthoi_diem_dat_xeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoi_diem_khoi_hanh", DbType="DateTime")]
		public System.Nullable<System.DateTime> thoi_diem_khoi_hanh
		{
			get
			{
				return this._thoi_diem_khoi_hanh;
			}
			set
			{
				if ((this._thoi_diem_khoi_hanh != value))
				{
					this.Onthoi_diem_khoi_hanhChanging(value);
					this.SendPropertyChanging();
					this._thoi_diem_khoi_hanh = value;
					this.SendPropertyChanged("thoi_diem_khoi_hanh");
					this.Onthoi_diem_khoi_hanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_xe", DbType="Int")]
		public System.Nullable<int> id_xe
		{
			get
			{
				return this._id_xe;
			}
			set
			{
				if ((this._id_xe != value))
				{
					this.Onid_xeChanging(value);
					this.SendPropertyChanging();
					this._id_xe = value;
					this.SendPropertyChanged("id_xe");
					this.Onid_xeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoi_diem_ket_thuc", DbType="DateTime")]
		public System.Nullable<System.DateTime> thoi_diem_ket_thuc
		{
			get
			{
				return this._thoi_diem_ket_thuc;
			}
			set
			{
				if ((this._thoi_diem_ket_thuc != value))
				{
					this.Onthoi_diem_ket_thucChanging(value);
					this.SendPropertyChanging();
					this._thoi_diem_ket_thuc = value;
					this.SendPropertyChanged("thoi_diem_ket_thuc");
					this.Onthoi_diem_ket_thucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
		public System.Nullable<int> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_ghe", DbType="Int")]
		public System.Nullable<int> so_ghe
		{
			get
			{
				return this._so_ghe;
			}
			set
			{
				if ((this._so_ghe != value))
				{
					this.Onso_gheChanging(value);
					this.SendPropertyChanging();
					this._so_ghe = value;
					this.SendPropertyChanged("so_ghe");
					this.Onso_gheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dat_xe", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_dat_xe
		{
			get
			{
				return this._id_dat_xe;
			}
			set
			{
				if ((this._id_dat_xe != value))
				{
					this.Onid_dat_xeChanging(value);
					this.SendPropertyChanging();
					this._id_dat_xe = value;
					this.SendPropertyChanged("id_dat_xe");
					this.Onid_dat_xeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
