#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavisUberCarOrderHandler
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="test_device_db")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCar_Order(Car_Order instance);
    partial void UpdateCar_Order(Car_Order instance);
    partial void DeleteCar_Order(Car_Order instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["test_device_dbConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Car_Order> Car_Orders
		{
			get
			{
				return this.GetTable<Car_Order>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Car_Order")]
	public partial class Car_Order : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _orderID;
		
		private string _origin_place;
		
		private string _destination_place;
		
		private string _car_type;
		
		private System.DateTime _pickup_time;
		
		private string _contact_number;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnorderIDChanging(int value);
    partial void OnorderIDChanged();
    partial void Onorigin_placeChanging(string value);
    partial void Onorigin_placeChanged();
    partial void Ondestination_placeChanging(string value);
    partial void Ondestination_placeChanged();
    partial void Oncar_typeChanging(string value);
    partial void Oncar_typeChanged();
    partial void Onpickup_timeChanging(System.DateTime value);
    partial void Onpickup_timeChanged();
    partial void Oncontact_numberChanging(string value);
    partial void Oncontact_numberChanged();
    #endregion
		
		public Car_Order()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orderID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int orderID
		{
			get
			{
				return this._orderID;
			}
			set
			{
				if ((this._orderID != value))
				{
					this.OnorderIDChanging(value);
					this.SendPropertyChanging();
					this._orderID = value;
					this.SendPropertyChanged("orderID");
					this.OnorderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_origin_place", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string origin_place
		{
			get
			{
				return this._origin_place;
			}
			set
			{
				if ((this._origin_place != value))
				{
					this.Onorigin_placeChanging(value);
					this.SendPropertyChanging();
					this._origin_place = value;
					this.SendPropertyChanged("origin_place");
					this.Onorigin_placeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_destination_place", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string destination_place
		{
			get
			{
				return this._destination_place;
			}
			set
			{
				if ((this._destination_place != value))
				{
					this.Ondestination_placeChanging(value);
					this.SendPropertyChanging();
					this._destination_place = value;
					this.SendPropertyChanged("destination_place");
					this.Ondestination_placeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_type", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string car_type
		{
			get
			{
				return this._car_type;
			}
			set
			{
				if ((this._car_type != value))
				{
					this.Oncar_typeChanging(value);
					this.SendPropertyChanging();
					this._car_type = value;
					this.SendPropertyChanged("car_type");
					this.Oncar_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pickup_time", DbType="DateTime NOT NULL")]
		public System.DateTime pickup_time
		{
			get
			{
				return this._pickup_time;
			}
			set
			{
				if ((this._pickup_time != value))
				{
					this.Onpickup_timeChanging(value);
					this.SendPropertyChanging();
					this._pickup_time = value;
					this.SendPropertyChanged("pickup_time");
					this.Onpickup_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contact_number", DbType="NChar(11) NOT NULL", CanBeNull=false)]
		public string contact_number
		{
			get
			{
				return this._contact_number;
			}
			set
			{
				if ((this._contact_number != value))
				{
					this.Oncontact_numberChanging(value);
					this.SendPropertyChanging();
					this._contact_number = value;
					this.SendPropertyChanged("contact_number");
					this.Oncontact_numberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
